const data = {
  meals: [
    {
      _id: "1",
      name: "Vegetable Ramen",
      description: "high quality product",
      price: 12,
      ingredients: "chiken",
      dietplanName: "keto",
      image: "/images/p1.jpg",
      rating: 4.5,
    },
    {
      _id: "2",
      name: "Fruit Salad",
      description: "high quality product",
      price: 12,
      ingredients: "chiken",
      dietplanName: "keto",
      image: "/images/p2.jpg",
      rating: 4.5,
    },
    {
      _id: "3",
      name: "Tofu salad",
      description: "high quality product",
      price: 12,
      ingredients: "chiken",
      dietplanName: "vegan",
      image: "/images/p3.jpg",
      rating: 4.5,
    },
    {
      _id: "4",
      name: "Vegetable pasta",
      description: "high quality product",
      price: 12,
      ingredients: "chiken",
      dietplanName: "vegetarian",
      image: "/images/p4.jpg",
      rating: 4.5,
    },
    {
      _id: "5",
      name: "Avocado rice",
      description: "high quality product",
      price: 12,
      ingredients: "chiken",
      dietplanName: "keto",
      image: "/images/p5.jpg",
      rating: 4.5,
    },
    {
      _id: "6",
      name: "Chiken Zukkini",
      description: "high quality product",
      price: 12,
      ingredients: "bean",
      dietplanName: "keto",
      image: "/images/p6.jpg",
      rating: 4.5,
    },
    {
      _id: "7",
      name: "Chicken & Goat Cheese Skillet",
      description: "high quality product",
      price: 12,
      ingredients: "bean",
      dietplanName: "keto",
      image: "/images/ketoChickenGoatCheeseSkillet.jpg",
      rating: 4.5,
    },
  ],
};
export default data;
